### ISSUE TITLE
Push Button JupyterHub on Carina

### ISSUE THREAD

**Issue by carolynvs** [jupyterhub/jupyterhub-carina#3]
I'd like to make it dirt simple for someone running a workshop to run JupyterHub on Carina. The idea being that with 1-2 commands they have a fully configured JupyterHub instance setup for them to run their class. No prior knowledge of how to setup and configure JupyterHub required.

* Generate a Let's Encrypt cert, if they have a domain, otherwise a self-signed cert
* JupyterHub is preconfigured with jupyterhub-carina
* Select the user image, and supply templates for the workshop

The end product would look something like this:

1. Create a Carina account and connect to a cluster.
2. Run a single command for one time setup (e.g. figure out your ip address, and make a safe spot for persistent data storage).
3. Note the IP address from the output above and update their DNS.
4. Run a single command to run the JupyterHub server.
5. The JupyterHub docker image handles cert generation, etc before starting up JupyterHub.

If we wanted to be super meta, this could be automated by howtowhale. So you'd log into howtowhale, and follow a notebook which walks you through these steps, handling everything for you except updating DNS.

**Comment by minrk** [comment]
Sounds great! If they use Rackspace DNS, you could even include that step.

**Comment by willingc** [comment]
@carolynvs Find me a PyCon later this week and let's see if we can push this forward together.

**Comment by carolynvs** [comment]
I made a ton of progress on this yesterday and have something working! Just need to figure out where to put it all. I'll submit a PR shortly and we can hash it out there.

**Comment by carolynvs** [comment]
See https://github.com/jupyterhub/jupyterhub-carina/pull/5#issuecomment-224133175
